### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by khirotaka** [khirotaka/Caramel#3]
開発環境 兼 実行環境として Docker-Composeが必要

```yml
version: “3”
services:
    web:
        ... # Webページ用
    ml:
        ... # 推論処理用
    drive:
        ... # 写真データ保存用
```

* `web` で画像の取り込み、推論結果からGoogle or Amazonへのリンクを吐く。画像は `drive` に保存。
* `ml` は `drive` に保存した画像を読み込み推論を行う。結果は `web` に渡す。
* `drive` は `web` が受け取った画像を保存し、必要に応じて `ml` に渡す。
